### PR TITLE
Fix sk path delimiters

### PR DESCRIPTION
**Pull request by davidsanner**
Quick fix: replace '/' with '.' for SK path   (btw, nice plugin!)

### CODE REVIEW

**Review by Asw1n — APPROVED** [review]

**Comment by Asw1n** [comment]
thanks

**Comment by davidsanner** [comment]
Thanks for your plugin.  I plan to use it instead of derived-data for true wind.  Looking forward to trying in light winds on a rolling boat.  Hopefully the sensor data is synced well enough to do the correction.

**Comment by Asw1n** [comment]
The plugin needs some real life evaluation indeed. I got a few hours of test data on standing water, that helps a bit. But it is hard as it is hard to isolate the effect of a single correction in noisy data.

**Comment by davidsanner** [comment]
Indeed, lots of variables that need evaluating / tuned. Nice to have them available in the plugin settings.  Just saw the smoothing value - again nice to have it adjustable.

My wind update is 10Hz (wired B&G) but currently I've got my attitude around 1Hz (Airmar -DST810) but with your plugin I should increase (via bluetooth app), at least if I want to try and cancel out induced wind from rolling/pitching in light winds.  Just having corrected wind when the boat is heeled on a long tack should be a solid improvement.

Lots of noise (especially in my speedo which I still need a better calibration)  garbage-in / garbage-out but the main corrections should go a long way.   Isolating variables and trying to correct for things like upwash must be tricky.  Might Influxdb / Grafana help?

I just enabled apparent wind correction - curious to see how my Furuno FI-501 wind display handles 2 130306 PGNs on the bus as I don't think I can configure its priority.

**Comment by davidsanner** [comment]
btw, just saw that environment.wind.directionTrue is showing up as negative.  I believe that is wind direction relative to true north so 0 to 2Pi rads.
Also would be nice to have environment.wind.directionMagnetic  (to fully replace derived-data wind calcs).  
I could open an issue and/or try a PR if you like.  Thx.

**Comment by Asw1n** [comment]
We have a similar setup. I  have the wireless B&G and also the Airmar. I am
thinking of another plugin to calculate (and apply) corrections for the
airmar. I did something before in Python and that was very useful for me.

Most displays allow you to select a source for PGN's. At least my Triton2
do.



Op do 19 dec 2024 om 22:33 schreef David Sanner ***@***.***>:

**Pull request merged**
